# 旧站 → 新站 手工对应（第一版）
# 等级：exact=内容一致 301；near=相近内容 301；todo=新站没有，暂时 302 到最接近的页面，等补内容后改 301
PAGE = {
    7:  ('公司介绍', '/profile', 'exact'),
    11: ('我们的客户', '/feedback_feedback', 'near'),
    12: ('联系我们', '/article/category/dimensional', 'near'),
    14: ('中心介绍', '/article/category/dimensional', 'exact'),
    15: ('企业教练服务', '/brand-courses-team4c', 'near'),
    16: ('进化教练', '/brand-courses-evolution', 'exact'),
    17: ('杉树计划', '/social_social', 'exact'),
    18: ('教练专业知识', '/article/category/encyclopedia', 'exact'),
    22: ('U型对话力', '/brand-courses-coach-social-theater', 'todo'),
    23: ('PCC教练技能提升', '/brand-courses-team-pcc', 'exact'),
    24: ('团队教练成长计划', '/brand-courses-team4c', 'exact'),
    25: ('《领导不适区》', '/article/5', 'near'),
    26: ('团队教练', '/brand-courses-team4c', 'exact'),
    27: ('高级进化教练', '/brand-courses-coach-senior', 'exact'),
    28: ('进化教练', '/brand-courses-evolution', 'exact'),
    29: ('杉树教练公益课', '/social_social', 'exact'),
    30: ('教练实践平台', '/ecology_practise', 'near'),
    31: ('教练认证', '/', 'near'),
    32: ('企业内训', '/brand-courses-team4c', 'near'),
    33: ('场租信息', '/article/category/dimensional', 'exact'),
    34: ('空间介绍', '/article/category/dimensional', 'exact'),
    35: ('最新活动', '/', 'todo'),
    36: ('上海中心', '/article/3', 'exact'),
    37: ('深圳中心', '/article/57', 'exact'),
    38: ('创问会员', '/', 'todo'),
    39: ('沙龙活动', '/', 'todo'),
    40: ('空间租用', '/article/category/dimensional', 'exact'),
    41: ('绩效教练', '/brand-courses-team4c', 'near'),
    42: ('U型创变领导力', '/brand-courses-coach-social-theater', 'todo'),
    43: ('教练型领导', '/brand-courses-team4c', 'near'),
    44: ('创建企业内部教练中心', '/brand-courses-team4c', 'near'),
    45: ('4C团队教练', '/brand-courses-team4c', 'exact'),
    46: ('核心教练团队', '/article/category/coachers', 'exact'),
    47: ('杉树计划', '/social_social', 'exact'),
    48: ('公益足迹', '/social_social', 'exact'),
    49: ('杉树计划', '/social_social', 'exact'),
    50: ('公益产品', '/social_social', 'exact'),
    51: ('国际教练认证体系', '/article/68', 'near'),
    52: ('核心稳定性', '/article/category/encyclopedia', 'todo'),
    55: ('教练专业知识', '/article/category/encyclopedia', 'exact'),
    56: ('PCC直通车', '/brand-courses-team-pcc', 'exact'),
    57: ('突破工作坊', '/', 'todo'),
    60: ('社会大剧院', '/brand-courses-coach-social-theater', 'exact'),
    61: ('4C团队教练', '/brand-courses-team4c', 'exact'),
    62: ('大事记', '/memorabilia_memorabilia', 'exact'),
    64: ('与教练对话', '/brand-courses-dialogue', 'exact'),
    66: ('一对一高管教练', '/article/category/coachers', 'todo'),
    70: ('4C团队教练讲师认证', '/brand-courses-team4c', 'exact'),
    71: ('咕噜教练', '/', 'todo'),
    72: ('纯净教练', '/brand-courses-significant', 'exact'),
    73: ('"I AM A COACH"第四届进化教练月', '/brand-courses-evolution', 'near'),
    75: ('女性领导力', '/', 'todo'),
    76: ('MCC大师级教练', '/brand-courses-coach-mcc', 'exact'),
    77: ('督导认证班', '/brand-courses-coach-supervisor', 'exact'),
}
LIST = {
    19: ('视频花絮', '/exciting_exciting', 'exact'),
    22: ('学员分享', '/feedback_feedback', 'near'),
    51: ('教练专业知识', '/article/category/encyclopedia', 'exact'),
    52: ('U型理论', '/article/9', 'todo'),
    53: ('企业教练', '/brand-courses-team4c', 'near'),
    54: ('教练技术应用', '/article/category/news', 'near'),
    55: ('大师级教练', '/article/category/advisor', 'near'),
    56: ('核心教练', '/article/category/coachers', 'exact'),
    58: ('团队教练', '/brand-courses-team4c', 'exact'),
    59: ('大师原创作品', '/cccoach_publishing_publishing', 'near'),
    63: ('美文赏析', '/article/category/news', 'todo'),
    64: ('教练行业资讯', '/article/category/news', 'exact'),
}
# 活动标题里出现这些词 → 对应课程页（按顺序匹配，先长后短）
ACTIVITY_KEYWORDS = [
    ('4C', '/brand-courses-team4c'), ('团队教练', '/brand-courses-team4c'),
    ('与教练对话', '/brand-courses-dialogue'), ('高级进化', '/brand-courses-coach-senior'), ('高阶进化', '/brand-courses-coach-senior'),
    ('进化PCC', '/brand-courses-team-pcc'), ('PCC直通车', '/brand-courses-team-pcc'), ('纯净PCC', '/brand-courses-pure-pcc'),
    ('纯净ACC', '/brand-courses-team-acc'), ('纯净教练', '/brand-courses-significant'), ('进化教练', '/brand-courses-evolution'),
    ('MCC', '/brand-courses-coach-mcc'), ('督导', '/brand-courses-coach-supervisor'),
    ('社会大剧院', '/brand-courses-coach-social-theater'), ('SPT', '/brand-courses-coach-social-theater'),
    ('演说', '/brand-courses-coach-speechmaker'), ('杉树', '/social_social'),
]
